// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & {
    // Group
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & {
    // Other fields
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | FooterSlice
  | ContactSlice
  | ServicesSlice
  | AboutSlice
  | HeroSlice
  | HeaderSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *About → Default → Primary → Key Text*
 */
export interface AboutSliceDefaultPrimaryKeyTextItem {
  /**
   * Key EN field in *About → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.key_text[].key_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key_en: prismic.KeyTextField;

  /**
   * Key PT field in *About → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.key_text[].key_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key_pt: prismic.KeyTextField;

  /**
   * Value EN field in *About → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.key_text[].value_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_en: prismic.KeyTextField;

  /**
   * Value PT field in *About → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.key_text[].value_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_pt: prismic.KeyTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Label EN field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.label_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_en: prismic.KeyTextField;

  /**
   * Label PT field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.label_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_pt: prismic.KeyTextField;

  /**
   * Quote Mark field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.quote_mark
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote_mark: prismic.KeyTextField;

  /**
   * Quote EN field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.quote_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote_en: prismic.KeyTextField;

  /**
   * Quote PT field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.quote_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote_pt: prismic.KeyTextField;

  /**
   * P1 EN field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.p1_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  p1_en: prismic.KeyTextField;

  /**
   * P1 PT field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.p1_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  p1_pt: prismic.KeyTextField;

  /**
   * P2 EN field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.p2_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  p2_en: prismic.KeyTextField;

  /**
   * P2 PT field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.p2_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  p2_pt: prismic.KeyTextField;

  /**
   * Key Text field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.key_text[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  key_text: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryKeyTextItem>>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Label EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_en: prismic.KeyTextField;

  /**
   * Label PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_pt: prismic.KeyTextField;

  /**
   * Title A EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title_a_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_a_en: prismic.KeyTextField;

  /**
   * Title A PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title_a_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_a_pt: prismic.KeyTextField;

  /**
   * Title B EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title_b_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_b_en: prismic.KeyTextField;

  /**
   * Title B PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title_b_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_b_pt: prismic.KeyTextField;

  /**
   * Blurb EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.blurb_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blurb_en: prismic.KeyTextField;

  /**
   * Blurb PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.blurb_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blurb_pt: prismic.KeyTextField;

  /**
   * Detail Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.detail_email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_email: prismic.KeyTextField;

  /**
   * Detail Hours EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.detail_hours_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_hours_en: prismic.KeyTextField;

  /**
   * Detail Hours PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.detail_hours_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_hours_pt: prismic.KeyTextField;

  /**
   * Detail Location field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.detail_location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_location: prismic.KeyTextField;

  /**
   * Label Name EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_name_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_name_en: prismic.KeyTextField;

  /**
   * Label Name PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_name_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_name_pt: prismic.KeyTextField;

  /**
   * Label Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_email: prismic.KeyTextField;

  /**
   * Label Message EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_message_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_message_en: prismic.KeyTextField;

  /**
   * Label Message PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.label_message_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_message_pt: prismic.KeyTextField;

  /**
   * Placeholder Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.placeholder_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_name: prismic.KeyTextField;

  /**
   * Placeholder Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.placeholder_email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_email: prismic.KeyTextField;

  /**
   * Placeholder Message EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.placeholder_message_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_message_en: prismic.KeyTextField;

  /**
   * Placeholder Message PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.placeholder_message_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_message_pt: prismic.KeyTextField;

  /**
   * Submit EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.submit_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_en: prismic.KeyTextField;

  /**
   * Submit PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.submit_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_pt: prismic.KeyTextField;

  /**
   * Sending EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.sending_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sending_en: prismic.KeyTextField;

  /**
   * Sending PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.sending_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sending_pt: prismic.KeyTextField;

  /**
   * Sent EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.sent_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sent_en: prismic.KeyTextField;

  /**
   * Sent PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.sent_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sent_pt: prismic.KeyTextField;

  /**
   * Error Name EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_name_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_name_en: prismic.KeyTextField;

  /**
   * Error Name PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_name_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_name_pt: prismic.KeyTextField;

  /**
   * Error Email Required EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_email_required_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_email_required_en: prismic.KeyTextField;

  /**
   * Error Email Required PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_email_required_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_email_required_pt: prismic.KeyTextField;

  /**
   * Error Email Invalid EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_email_invalid_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_email_invalid_en: prismic.KeyTextField;

  /**
   * Error Email Invalid PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_email_invalid_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_email_invalid_pt: prismic.KeyTextField;

  /**
   * Error Message EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_message_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_message_en: prismic.KeyTextField;

  /**
   * Error Message PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_message_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_message_pt: prismic.KeyTextField;

  /**
   * Error Network EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_network_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_network_en: prismic.KeyTextField;

  /**
   * Error Network PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.error_network_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  error_network_pt: prismic.KeyTextField;

  /**
   * Required EN field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.required_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  required_en: prismic.KeyTextField;

  /**
   * Required PT field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.required_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  required_pt: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Copy field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copy: prismic.KeyTextField;

  /**
   * Legal field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  legal: prismic.KeyTextField;

  /**
   * Built field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.built
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  built: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Brand Mark field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.brand_mark
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_mark: prismic.KeyTextField;

  /**
   * Nav About EN field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_about_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_about_en: prismic.KeyTextField;

  /**
   * Nav About PT field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_about_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_about_pt: prismic.KeyTextField;

  /**
   * Nav Services EN field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_services_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_services_en: prismic.KeyTextField;

  /**
   * Nav Services PT field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_services_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_services_pt: prismic.KeyTextField;

  /**
   * Nav Contact EN field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_contact_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_contact_en: prismic.KeyTextField;

  /**
   * Nav Contact PT field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.nav_contact_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_contact_pt: prismic.KeyTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Meta Top EN field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.meta_top_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_top_en: prismic.KeyTextField;

  /**
   * Meta Top PT field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.meta_top_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_top_pt: prismic.KeyTextField;

  /**
   * Name A field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name_a
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_a: prismic.KeyTextField;

  /**
   * Name B field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name_b
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_b: prismic.KeyTextField;

  /**
   * Tag EN field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tag_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_en: prismic.KeyTextField;

  /**
   * Tag PT field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tag_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_pt: prismic.KeyTextField;

  /**
   * Scroll EN field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.scroll_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  scroll_en: prismic.KeyTextField;

  /**
   * Scroll PT field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.scroll_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  scroll_pt: prismic.KeyTextField;

  /**
   * Index L EN field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.index_l_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  index_l_en: prismic.KeyTextField;

  /**
   * Index L PT field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.index_l_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  index_l_pt: prismic.KeyTextField;

  /**
   * Index R field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.index_r
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  index_r: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Services → Default → Primary → Key Text*
 */
export interface ServicesSliceDefaultPrimaryKeyTextItem {
  /**
   * Name A EN field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].name_a_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_a_en: prismic.KeyTextField;

  /**
   * Name A PT field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].name_a_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_a_pt: prismic.KeyTextField;

  /**
   * Name B EN field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].name_b_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_b_en: prismic.KeyTextField;

  /**
   * Name B PT field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].name_b_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_b_pt: prismic.KeyTextField;

  /**
   * Desc EN field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].desc_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  desc_en: prismic.KeyTextField;

  /**
   * Desc PT field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].desc_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  desc_pt: prismic.KeyTextField;

  /**
   * Price EN field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].price_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_en: prismic.KeyTextField;

  /**
   * Price PT field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].price_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_pt: prismic.KeyTextField;

  /**
   * Duration EN field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].duration_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration_en: prismic.KeyTextField;

  /**
   * Duration PT field in *Services → Default → Primary → Key Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[].duration_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  duration_pt: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Label EN field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.label_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_en: prismic.KeyTextField;

  /**
   * Label PT field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.label_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_pt: prismic.KeyTextField;

  /**
   * Title EN field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.title_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_en: prismic.KeyTextField;

  /**
   * Title PT field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.title_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_pt: prismic.KeyTextField;

  /**
   * Count EN field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.count_en
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  count_en: prismic.KeyTextField;

  /**
   * Count PT field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.count_pt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  count_pt: prismic.KeyTextField;

  /**
   * Key Text field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.key_text[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  key_text: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryKeyTextItem>
  >;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryKeyTextItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryKeyTextItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
